version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: flower_exhibit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flower-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flower_exhibit"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: flower_exhibit
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - flower-network

networks:
  flower-network:
    driver: bridge
